### ISSUE TITLE
Is this set up already?

### ISSUE THREAD

**Issue by spences10** [chingubotsteam5/easy-peasy-bot#1]
Do we have a token?

**Comment by drguildo** [comment]
I do but this is just a test bot that I'm modifying and running locally to learn about Slack/Botkit etc.

**Comment by spences10** [comment]
Ok, so there's not one set up on the slack channel @drguildo?

**Comment by drguildo** [comment]
I added it to #bots-team-5-testing but it only does anything when I have it running on my machine and localtunnel isn't being crap (not very often).

Like I say, it's just for me to use to test while I learn stuff. We're not limited to a single bot or a single Slack app or a single API key or anything like that.
